config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  #users
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'

  #Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :users
  resources :events do
    post 'attend', on: :member
    post 'unattend', on: :member
    post 'invite', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :user_attendees, :class_name => 'User', :join_table => :events_users
    belongs_to :creator, :class_name => 'User'
    validates :name,  presence: true, uniqueness: true
    validates :description,  presence: true
    validates :date,  presence: true
    validates :place,  presence: true

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :authored_events, :foreign_key => :creator_id, :class_name => 'Event'
    has_and_belongs_to_many :attended_events, :class_name => 'Event', :join_table => :events_users
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 8 }, on: :create
  	has_secure_password

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

def login_required
    if current_user.blank?
        redirect_to('/') 
        flash[:danger] = "Connecte toi pour accéder à ta page !"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    if logged_in?
      @event = Event.new
    else
      flash[:danger] = "Connecte toi pour créer événement !"
      redirect_to login_path
    end
  end

  def create
    @user = current_user
    @event = @user.authored_events.new(event_params)
    if @event.save
      flash[:success] = "L'événement a bien été créé !"
      redirect_to current_user
      @event.user_attendees << current_user
      @event.save
    else
      render 'new'
    end
  end

  def event_params
     params.require(:event).permit(:name, :description, :date, :place)
  end

  def show
    if logged_in?
      @event = Event.find(params[:id])
      @users = User.all
    else
      flash[:danger] = "Connecte toi pour accéder à l'événement !"
      redirect_to login_path
    end
  end

  def index
    @events = Event.all
  end

  def attend
    if logged_in?
      @event = Event.find(params[:id])
      @event.user_attendees << current_user
      @event.save
      flash[:success] = "Vous êtes inscrit à l'événement !"
      redirect_to events_path
    else
      redirect_to login_path
    end
  end

  def invite
    @event = Event.find(params[:id])
    @user = User.find(params[:user])
    @event.user_attendees << @user
    @event.save
    flash[:success] = "Vous avez ajouté votre ami à l'événement !"
    redirect_to @event
  end

  def unattend
    @event = Event.find(params[:id])
    @event.user_attendees.delete(current_user)
    @event.save
    flash[:success] = "Vous êtes désinscrit !"
    redirect_to current_user
  end

  def destroy
    @user = current_user
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Évenement supprimé !"
    redirect_to @current_user
  end

  def edit
    @user =  current_user
    @event = Event.find(params[:id])
    if logged_in? && current_user == @user
      edit_event_path
    else
      redirect_to login_path
    end
  end

  def update
      @user = current_user
      @event = Event.find(params[:id])
      if logged_in? && @current_user == @user
        if @event.update_attributes(event_params)
           flash[:success] = "Événement edité !"
           redirect_to event_path
       else
          render 'edit'
       end
     else
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/name combination'
      render 'new'
    end
  end

    def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except:[:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Bienvenue !"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if logged_in? && current_user == @user
      user_path
    else
      redirect_to login_path
    end
  end

  def update
      @user = User.find(params[:id])
      if logged_in? && @current_user == @user
      if @user.update_attributes(user_params)
        flash[:success] = "Profil edité !"
        redirect_to user_path
       else
       render 'edit'
     end
     else
      redirect_to login_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    log_out
    @user.destroy
    flash[:success] = "Ton compte a été supprimé !"
    redirect_to root_path
  end

  private

  def user_params
      params.require(:user).permit(:id, :name, :email, :password_digest, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Le meilleur site d'événements"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<% provide(:title, 'Nouvel événement') %>
<h1>Édite l'événement</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: event_path) do |f| %>
    <%= render 'shared/error_event_messages' %>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-glass"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
      <%= f.text_field :description, class: 'form-control', placeholder: "Description" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      <%= f.date_field :date, class: 'form-control', placeholder: "Date" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
      <%= f.text_field :place, class: 'form-control', placeholder: "Lieu" %>
    </div>
    <br>
    <%= f.submit "Éditer l'événement", class: "btn btn-sm btn-primary", method: :patch %>
    <% end %>
  </div>

app/views/events/index.html.erb
<% provide(:title, "Événements") %>
<h1>Tous les événements</h1>
<br>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Nom</th>
        <th>Date</th>
        <th>Lieu</th>
        <th><i class="em em-eye"></th>
        <% if logged_in? %>
            <th>Participation</th>
        <% end %>
    </tr>
    <% @events.each do |e|%>
    <tr>
        <td> <%= e.name %> </td>
        <td> <%= e.date.strftime("%d/%m/%Y ") unless e.date.nil? %>  </td>
        <td> <%= e.place %> </td>
        <td> <%= link_to "Voir", e, class: "btn btn-sm btn-info", style:"width:35%;" %> </td>
        <% if logged_in? %>
            <% if e.user_attendees.include?(current_user) %>
                <td class="text-success"> Inscris </td>
            <% elsif e.date > Time.now %>  
                <td style="width:10%;"> <%= button_to 'Rejoindre', attend_event_path(e), method: :post, confirm: 'really?',  class: "btn btn-sm btn-primary" %> </td>  
            <% else %>
                <td></td>
            <% end %>
        <% end %>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/events/new.html.erb
<% provide(:title, 'Nouvel événement') %>
<h1>Nouvel événement</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: events_path) do |f| %>
    <%= render 'shared/error_event_messages' %>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-glass"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
      <%= f.text_field :description, class: 'form-control', placeholder: "Description" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      <%= f.date_field :date, class: 'form-control', placeholder: "Date" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
      <%= f.text_field :place, class: 'form-control', placeholder: "Lieu" %>
    </div>
    <br>
    <%= f.submit "Créer un nouvel événement", class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="container">
  <h1>Informations sur l'événement</h1>
    <br>
    <h2><strong>Createur :</strong> <%= @event.creator.name.capitalize %></h2>
    <br>
    <table class="table table-striped table-hover">
      <tr>
         <th><strong> Nom :</strong></th>
         <th><strong>Date :</strong></th> 
         <th><strong>Description :</strong></th>
         <th><strong>Lieu :</strong></th>
      </tr>
      <tr>
       <td> <%= @event.name %> </td>
       <td> <%= @event.date.strftime("%d/%m/%Y ") unless @event.date.nil? %> </td>
       <td> <%= @event.description %> </td>
       <td> <%= @event.place %> </td>
      </table>
      <br>
      <% if logged_in? %>
        <% if @event.user_attendees.include?(current_user) %>
          <h3 class="btn btn-sm btn-info" style="width:30%; margin-left:35%;"> Vous participez à cet événement </h3>
          <br>
          <h3><%= button_to 'Désinscription', unattend_event_path(@event), method: :post, confirm: 'really?',  class: "btn btn-sm btn-danger", style: "width:30%; margin-left:35%;" %></h3> 
        <% elsif @event.date > Time.now %>  
          <%= button_to 'Rejoindre', attend_event_path(@event), method: :post, confirm: 'really?',  class: "btn btn-sm btn-primary", style: "width:30%; margin-left:35%;" %>
        <% end %>
      <% else %>
        <%= link_to "Inscris toi pour participer !", login_path, class: "btn btn-sm btn-primary", style:"width:30%; margin-left:35%;" %>
      <% end %>
      <% if @event.creator == current_user %>
        <h3 class="btn btn-sm btn-warning" style="width:30%; margin-left:35%;"> Vous êtes le créateur de l'événement </h3>
        <h3><%= link_to "Editer", edit_event_path, method: :get, class:"btn btn-sm btn-primary", style:"width:30%; margin-left:35%;" %></h3>
      <h3> <%= link_to "Supprimer", event_path, method: :delete, class:"btn btn-sm btn-danger", style:"width:30%; margin-left:35%;", data: {confirm: 'Etes vous sur?' } %></h3>
      <% end %>
      <br>
      <br>
      <% if logged_in? %>
      <div>
        <h1>Utilisateurs inscris</h1>
        <table class="table table-striped table-hover">
          <tbody>
            <tr>
              <th>Nom</th>
              <th>Email</th>
            </tr>
            <% @event.user_attendees.each do |u|%>
            <tr>
               <td> <%= u.name %> </td>
               <td> <%= u.email %> </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
      <br>
      <br>
      <% if logged_in? && @event.date > Time.now %>
      <div>
        <h1>Ajouter un ami</h1>
          <table class="table table-striped table-hover">
            <tbody>
              <tr>
                <th>Nom</th>
                <th>Email</th>
                <th></th>
              </tr>
            <% @users.each do |u|%>
              <% if !(@event.user_attendees.include?(u)) && u != current_user %>
              <tr>
                <td> <%= u.name %> </td>
                <td> <%= u.email %> </td>
                <td> <%= button_to 'Inviter', invite_event_path(@event), method: :post,  class: "btn btn-sm btn-warning", :params => {:user => u} %> </td>
              </tr>
              <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom" style="display:flex; justify-content:left; flex-wrap:wrap;">
    <div class="nav navbar-nav" style="float:none;" >
    <nav>
        <ul>
            <li>
               Ce site a été fait avec <i class="em em-blue_heart"></i>
            </li>
        </ul>
    </nav>
    </div>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title>
        <%= full_title(yield(:title)) %>
    </title>
    <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                <%= render 'layouts/shim' %>
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "les maxi-soirées", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Evènements", events_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Compte <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Connexion", login_path, class: 'link-to-text-color' %></li>
          <li><%= link_to "Inscription", signup_path, class: 'link-to-text-color' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
     <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
     </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body>
    <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>">
                    <%= message %>
                </div>
                <% end %>
                    <%= yield %>
                            <%= debug(params) if Rails.env.development? %>
        </div>
</body>
</html>

app/views/shared/_error_event_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Bienvenue</h1>
<br/>
<div align="center">
<p>Ici sont recensés les évènements légaux et illégaux les plus prisés d'Europe.</p>
<p>Que tu préfères enflammer le dancefloor ou taper du pied après un bon rail de coco, ce site est fait pour toi ! </p>
</div>

<%= link_to root_path do %>
  <div style="float:right; width: 50%">
  	<%= image_tag('tomorrowland-2012.jpg') %>
  </div>
<% end %>
<%= link_to root_path do %>
  	<div style="float:left;">
  <%= image_tag('booba.jpg') %>
  </div>
<% end %>


<br/> <br/> <br/> <br/> <br/>
<div align="center">
<%= link_to "Inscris toi vite !", signup_path, class: "btn btn-danger" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, 'Inscription') %>
<h1>Édite ton profil !</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: user_path) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmation" %>
    </div>
    <br>
      <%= f.submit "Valider", class: "btn btn-sm btn-primary" %>
    <% end %>
    <br>
    <% if current_user == @user %>
      <%= form_for @user, method: :delete do |f| %>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
    </div>
    <br>
    <span align="center"><%= f.submit "Supprimer le compte", class: "btn btn-sm btn-primary", data: {confirm: 'Etes vous sur?' } %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Inscription') %>
<h1>Inscription</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmation" %>
    </div>
    <br>
    <%= f.submit "Crée ton compte !", class: "btn btn-sm btn-primary", style: "width:70%; margin-left:15%" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
      <h1>Ton profil</h1>
</div>
<div>
    <section class="user_info">
      <h2>
        Nom : <%= @user.name %>
      </h2>
      <h2>
       Email : <%= @user.email %>
      </h2>
      <% if current_user == @user %>
      <%= form_tag edit_user_path(@user), method: 'get' do %>
          <input style="width:20%; margin-left:40%" type="submit" value="Editer" class="btn btn-sm btn-primary">
      <% end %>
    <% end %>
    </section>
</div>
<br>
<br>
<div>
<h1>Événements créés</h1>
<br>
<table class="table table-striped table-hover">
    <tr>
        <th>Non</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th><i class="em em-eye"></i></th>
        <th><i class="em em-skull"></i></th>
    </tr>
    <% current_user.authored_events.each do |e|%>
    <tr>
        <td> <%= e.name %> </td>
        <td> <%= e.description %> </td>
        <td> <%= e.date.strftime("%d/%m/%Y ") unless e.date.nil? %>  </td>
        <td> <%= e.place %> </td>
        <td> <%= button_to "Voir", e, method: :get, class:"btn btn-sm btn-primary", style:"width:100%;" %> </td>
        <% if e.creator == current_user %>
        <td> <%= button_to "Supprimer", e, method: :delete, class:"btn btn-sm btn-danger", style:"width:60%;", data: {confirm: 'Etes vous sur?' } %></td>
        <% end %>
    </tr>
    <% end %>
</table>
</div>
<div class="center">
  <%= link_to "Nouvel événement", new_event_path, class: "btn btn-sm btn-primary" %>
</div> 
<br>
<br>
<div>
<h1>Évenement à venir</h1>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th><i class="em em-eye"></i></th>
        <th><i class="em em-flying_saucer"></i></th>
    </tr>
    <% current_user.attended_events.each do |e|%>
        <% if e.date > Time.now %>
        <tr>
            <td> <%= e.name %> </td>
            <td> <%= e.description %> </td>
            <td> <%= e.date.strftime("%d/%m/%Y ") %>  </td>
            <td> <%= e.place %> </td>
            <td> <%= button_to "Voir", e, method: :get, class:"btn btn-sm btn-primary", style:"width:100%;" %> </td>
              <td> <%= button_to "Se désinscrire", unattend_event_path(e), method: :post, class:"btn btn-sm btn-danger", style:"width:70%;", data: {confirm: 'Etes vous sur?' } %> </td>
        </tr>
        <% end %>
    <% end %>
    </tbody>
</table>
</div> 
<br>  
<br>
<div>
<h1>Évenement passé</h1>
<br>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th><i class="em em-eye"></th>
    </tr>
    <% current_user.attended_events.each do |e|%>
      <% if e.date < Time.now %>
      <tr>
          <td> <%= e.name %> </td>
          <td> <%= e.description %> </td>
          <td> <%= e.date.strftime("%d/%m/%Y ") unless e.date.nil? %>  </td>
          <td> <%= e.place %> </td>
          <td> <%= link_to "Voir", e %> </td>
      </tr>
      <% end %>
    <% end %>
    </tbody>
</table>
</div>